'use strict';
const fullName = 'Katelyn Ngo';
const isCool = true;
const totalPets = 1;
console.log(' Value of Full Name:', fullName);
console.log('Value of isCool:', isCool);
console.log('Value of totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('type of isCool:', typeof true);
console.log('typeof totalPets:', typeof 1);
const empty = null;
console.log('value of empty:', empty);
console.log('typeof empty:', typeof empty);
let nothing;
console.log('Value of nothing:', nothing);
console.log('type of nothing:', nothing);
