'use strict';
const colors = ['red', 'white', 'blue'];
const firstColor = colors[0];
const secondColor = colors[1];
const thirdColor = colors[2];
console.log('value of colors[0]:', firstColor);
console.log('value of colors[1]:', secondColor);
console.log('value of colors[2]:', thirdColor);
const AmericaColors = `America is ${firstColor} ${secondColor} ${thirdColor}`;
console.log(AmericaColors);
colors[2] = 'green';
const MexicoColors = `Mexico is ${firstColor} ${secondColor} ${thirdColor}`;
console.log(MexicoColors);
console.log('value of colors:', colors);
console.log('typeof colors:', typeof colors);
const students = ['charlie', 'billy', 'ken', 'ben'];
const numberOfStudents = students.length;
console.log('There are four students:', numberOfStudents);
const lastIndex = numberOfStudents - 1;
console.log('the last student in array is', lastIndex);
const lastStudent = students[lastIndex];
console.log(`the last student in the array is ${lastStudent}`);
console.log('value of students', students);
