'use strict';
const width = 2;
const height = 3;
const area = height * width;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 3;
const payment = 4;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 6;
const midterm = 7;
const final = 8;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Katelyn';
const lastName = ' Ngo';
const fullName = firstName + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 6;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 10;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
